INSERT INTO user (username, email, introduction, password, pict) values ("test", "test@mail", "test", "e10adc3949ba59abbe56e057f20f883e", "1.png");
INSERT INTO user (username, email, introduction, password, pict) values ("hara", "hara@mail", "I like TV!", "e10adc3949ba59abbe56e057f20f883e", "2.png");
INSERT INTO user (username, email, introduction, password, pict) values ("tanaka", "tanaka@mail", "HELLO!", "e10adc3949ba59abbe56e057f20f883e", "3.png");
INSERT INTO user (username, email, introduction, password, pict) values ("suzuki", "suzuki@mail", "hello !", "e10adc3949ba59abbe56e057f20f883e", "4.png");
INSERT INTO user (username, email, introduction, password, pict) values ("hayashi", "hayashi@mail", "Hey !", "e10adc3949ba59abbe56e057f20f883e", "5.png");
INSERT INTO user (username, email, introduction, password, pict) values ("sato", "sato@mail", "Nice to meet you!", "e10adc3949ba59abbe56e057f20f883e", "6.png");
INSERT INTO user (username, email, introduction, password, pict) values ("nakata", "nakata@mail", "I'm nakata!", "e10adc3949ba59abbe56e057f20f883e", "7.png");
INSERT INTO user (username, email, introduction, password, pict) values ("harada", "harada@mail", "hello!", "e10adc3949ba59abbe56e057f20f883e", "8.png");
INSERT INTO user (username, email, introduction, password) values ("ito", "ito@mail",  "hello!", "e10adc3949ba59abbe56e057f20f883e");
INSERT INTO user (username, email, introduction, password) values ("iida", "iida@mail", "hello !!!!!!!!!!", "e10adc3949ba59abbe56e057f20f883e");
INSERT INTO user (username, email, introduction, password) values ("nishino", "nishino@mail", "ya!","e10adc3949ba59abbe56e057f20f883e");
INSERT INTO user (username, email, introduction, password) values ("higashino", "higashino@mail", "nice!", "e10adc3949ba59abbe56e057f20f883e");

INSERT INTO stations values (1, "NHK総合・東京","東京都渋谷区神南二丁目2番1号");
INSERT INTO stations values (2,"NHKEテレ・東京","東京都渋谷区神南二丁目2番1号");
INSERT INTO stations values (4,"日テレ","東京都港区東新橋1丁目6番1号");
INSERT INTO stations values (5,"テレビ朝日","東京都港区六本木六丁目9番1号");
INSERT INTO stations values (6,"TBS","東京都港区赤坂5丁目3番6号");
INSERT INTO stations values (7,"テレビ東京","東京都港区六本木3丁目2番1号");
INSERT INTO stations values (8,"フジテレビ","東京都港区台場2丁目4番8号");
INSERT INTO stations values (9,"TOKYO MX","東京都千代田区麹町1丁目12番地");

INSERT INTO program (id, name, station_id, start, end, day, description) values (1, "水曜日のダウンタウン", 6, "22:00", "23:00", "水", "個人が信じ込む「説」を芸能人がプレゼン｡その「説」についてスタジオで激論を交わしながら展開していく｡");
INSERT INTO program (id, name, station_id, start, end, day, description) values (2, "あちこちオードリー", 7, "23:00", "23:50", "水", "今注目の有名人をゲストに迎え、本音トークを展開！ 盛り上がること間違いなしの、ぶっちゃけトーク番組！");
INSERT INTO program (id, name, station_id, start, end, day, description) values (3, "ラヴィット", 6, "08:00", "09:55", "平日", "日本でいちばん明るい朝番組。『ラヴィット！』");
INSERT INTO program (id, name, station_id, start, end, day, description) values (4, "激レアさんを連れてきた。", 5, "23:15", "23:45", "月", "激レアに遭遇した人=激レアさんを研究サンプルとしてスタジオに集め、その体験を徹底取材＆研究発表します!");
INSERT INTO program (id, name, station_id, start, end, day, description) values (5, "有吉の壁", 4, "19:00", "20:00", "水", "MC有吉弘行が「壁」となってそこに次世代を担うお笑い芸人が挑む、とにかく「笑い」を追求した、新時代のお笑い番組。お笑い猛者は有吉の笑いの「壁」を越えられるのか!?");
INSERT INTO program (id, name, station_id, start, end, day, description) values (6, "ワンピース", 8, "09:30", "10:00", "日", "1997年に航海は始まった。週刊少年ジャンプで連載が開始されるや、空前絶後の人気を獲得し、今や国民的娯楽となった『ワンピース』");
INSERT INTO program (id, name, station_id, start, end, day, description) values (7, "100カメ", 1, "23:00", "23:30", "火", "１００カメは、気になる場所に１００台の固定カメラを設置して人々の生態を観察するドキュメンタリー。カメラを意識しない姿・会話の記録から、思わぬ実像が見えてくる。");

INSERT INTO program (id, name, station_id, start, end, day, description) values (8, "世界まる見え!テレビ特捜部 ", 4, "19:00", "20:00", "月", "世界の不思議＆ちょっと笑える映像大連発！");
INSERT INTO program (id, name, station_id, start, end, day, description) values (9, "帰れマンデー見っけ隊!!", 5, "19:00", "20:32", "月", "旅番組！");
INSERT INTO program (id, name, station_id, start, end, day, description) values (10, "クレイジージャーニー ", 6, "21:00", "22:00", "月", "独自の視点やこだわりを持って世界&日本を巡る“クレイジージャーニーが体験を語る!!");
INSERT INTO program (id, name, station_id, start, end, day, description) values (11, "news zero", 4, "23:00", "23:59", "平日", "報道番組");
INSERT INTO program (id, name, station_id, start, end, day, description) values (12, "news 23", 6, "23:00", "23:56", "平日", "ニュースの現場・当事者を取材することにこだわります。スタジオには、最先端の専門知識を持つ識者・今最も旬であるゲストを呼び、時代の半歩先を行く情報を、正確に速くお伝えします。");
INSERT INTO program (id, name, station_id, start, end, day, description) values (13, "ヒューマングルメンタリー オモウマい店", 4, "19:00", "19:54", "火", "ヒューマングルメンタリー オモウマい店！！！！！");
INSERT INTO program (id, name, station_id, start, end, day, description) values (14, "ロンドンハーツ", 5, "23:15", "23:45", "火", "バラエティー番組");
INSERT INTO program (id, name, station_id, start, end, day, description) values (15, "うたコン", 1, "19:57", "20:42", "火", "生放送! NHK歌番組");
INSERT INTO program (id, name, station_id, start, end, day, description) values (16, "プレバト!! ", 6, "19:00", "20:00", "木", "人気芸能人に才能があるのか！専門家が査定しランキングを発表！");
INSERT INTO program (id, name, station_id, start, end, day, description) values (17, "ニンゲン観察バラエティ モニタリング", 6, "20:00", "21:00", "木", "お笑いか？ドキュメンタリーか？日本中でニンゲンの行動を観察！“もしも”の場面に遭遇したらアナタはどうしますか？");
INSERT INTO program (id, name, station_id, start, end, day, description) values (18, "秘密のケンミンSHOW極", 4, "21:00", "22:00", "木", "ディスカバリーエンターテインメント番組！日本全国の激うまグルメや衝撃の習慣を徹底調査！あなたの知らない日本が明らかに！？");
INSERT INTO program (id, name, station_id, start, end, day, description) values (19, "金曜ロードショー", 4, "21:00", "23:04", "金", "映画");
INSERT INTO program (id, name, station_id, start, end, day, description) values (20, "人志松本の酒のツマミになる話 ", 8, "21:58", "22:52", "金", "『人志松本の酒のツマミになる話』は“お酒の席が盛り上がれば何をしゃべってもＯＫ”というルールの下、普段言えないような悩みや失敗談、心に秘めた本音を語り合うトークバラエティー。");
INSERT INTO program (id, name, station_id, start, end, day, description) values (21, "全力!脱力タイムズ ", 8, "23:00", "23:40", "金", "見どころ満載の『全力！脱力タイムズ』をお見逃しなく！");
INSERT INTO program (id, name, station_id, start, end, day, description) values (22, "芸能人が本気で考えた!ドッキリGP ", 8, "19:00", "20:00", "土", "ドッキリ番組");
INSERT INTO program (id, name, station_id, start, end, day, description) values (23, "嗚呼!!みんなの動物園 ", 4, "19:00", "19:58", "土", "どうぶつ番組");
INSERT INTO program (id, name, station_id, start, end, day, description) values (24, "相葉マナブ", 5, "18:00", "19:00", "日", "嵐の相葉くんが日本の素晴らしさを学ぶため、旬の食材で究極の料理作りに挑戦したり、いろんなものを手作りしたり体験学習をしながら成長していくロケバラエティー");
INSERT INTO program (id, name, station_id, start, end, day, description) values (25, "有吉ぃぃeeeee!〜そうだ!今からお前んチでゲームしない?", 7, "21:54", "22:48", "日", "ゲーム愛の強さでは誰にも負けない“芸能界随一のゲーマー”有吉弘行が、本気でゲーム！毎回、芸人、アイドルから、芸能界の重鎮まで“ゲーム好き”そうな芸能人の家へ行き、話題の“eスポーツ”に挑戦する。");
INSERT INTO program (id, name, station_id, start, end, day, description) values (26, "あざとくて何が悪いの?", 5, "23:55", "0:25", "日", "猛毒注意‼山里亮太×田中みな実×弘中綾香という危険すぎる３人が“あざとい男女”の言動について徹底トーク‼");

INSERT INTO celebrity values (1, "松本人志", "吉本興業");
INSERT INTO celebrity values (2, "浜田雅功", "吉本興業");
INSERT INTO celebrity values (3, "ダウンタウン", "吉本興業");
INSERT INTO celebrity values (4, "春日俊彰", "ケイダッシュステージ");
INSERT INTO celebrity values (5, "若林正恭", "ケイダッシュステージ");
INSERT INTO celebrity values (6, "オードリー", "ケイダッシュステージ");
INSERT INTO celebrity values (7, "川島明", "吉本興業");
INSERT INTO celebrity values (8, "田村真子", "TBS");
INSERT INTO celebrity values (9, "弘中綾香", "テレビ朝日");
INSERT INTO celebrity values (10, "有吉弘行", "太田プロダクション");
INSERT INTO celebrity values (11, "佐藤栞里", "スターダストプロモーション");
INSERT INTO celebrity values (12, "田中真弓", "青二プロダクション");
INSERT INTO celebrity values (13, "中井和哉", "青二プロダクション");
INSERT INTO celebrity values (14, "岡村明美", "マウスプロモーション");
INSERT INTO celebrity values (15, "平田広明", "ひらたプロダクションジャパン");
INSERT INTO celebrity values (16, "山口勝平", "有限会社悟空");
INSERT INTO celebrity values (17, "大谷育江", "マウスプロモーション");
INSERT INTO celebrity values (18, "山口由里子", "青二プロダクション");
INSERT INTO celebrity values (19, "矢尾一樹", "マック・ミック");
INSERT INTO celebrity values (20, "チョー", "東京俳優生活協同組合");
INSERT INTO celebrity values (21, "宝亀克寿", "青二プロダクション");

INSERT INTO perform values(1, 1, "MC");
INSERT INTO perform values(1, 2, "MC");
INSERT INTO perform values(1, 3, "MC");
INSERT INTO perform values(2, 4, "大将");
INSERT INTO perform values(2, 5, "常連客");
INSERT INTO perform values(2, 6, "MC");
INSERT INTO perform values(3, 7, "MC");
INSERT INTO perform values(3, 8, "アナウンサー");
INSERT INTO perform values(4, 9, "研究助手");
INSERT INTO perform values(4, 5, "研究員");
INSERT INTO perform values(5, 10, "MC");
INSERT INTO perform values(5, 11, "MC");
INSERT INTO perform values(6, 12, "ルフィ");
INSERT INTO perform values(6, 13, "ゾロ");
INSERT INTO perform values(6, 14, "ナミ");
INSERT INTO perform values(6, 16, "ウソップ");
INSERT INTO perform values(6, 15, "サンジ");
INSERT INTO perform values(6, 17, "チョッパー");
INSERT INTO perform values(6, 18, "ロビン");
INSERT INTO perform values(6, 19, "フランキー");
INSERT INTO perform values(6, 20, "ブルック");
INSERT INTO perform values(6, 21, "ジンベエ");
INSERT INTO perform values(7, 4, "MC");
INSERT INTO perform values(7, 5, "MC");
INSERT INTO perform values(7, 6, "MC");

INSERT INTO favorite values(1, 1, 1);
INSERT INTO favorite values(1, 2, 1);
INSERT INTO favorite values(1, 5, 1);
INSERT INTO favorite values(1, 4, 1);
INSERT INTO favorite values(2, 5, 1);
INSERT INTO favorite values(2, 6, 1);
INSERT INTO favorite values(2, 7, 1);
INSERT INTO favorite values(3, 8, 1);
INSERT INTO favorite values(3, 9, 1);
INSERT INTO favorite values(4, 11, 1);
INSERT INTO favorite values(5, 12, 1);
INSERT INTO favorite values(5, 10, 1);
INSERT INTO favorite values(5, 13, 1);
INSERT INTO favorite values(5, 14, 1);
INSERT INTO favorite values(6, 13, 1);
INSERT INTO favorite values(6, 16, 1);
INSERT INTO favorite values(7, 18, 1);
INSERT INTO favorite values(8, 19, 1);